# 默认设置
default:
  groupGlobalCD: 0 # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 1000 # 群聊中个人操作冷却时间，单位毫秒

  onlyReplyAt: 0 # 是否只仅关注主动@机器人的消息， 0-否 1-是 2-触发用户非主人只回复@机器人的消息及特定前缀的消息，主人免前缀
  botAlias:
    - 云崽
    - 云宝

  imgAddLimit: 0 #添加表情是否限制  0-所有群员都可以添加 1-群管理员才能添加 2-主人才能添加
  imgMaxSize: 2 #添加表情图片大小限制，默认2m
  addPrivate: 1 #是否允许私聊添加  1-允许 0-禁止

  enable: []

  #禁用功能，功能名称,例如：十连、角色查询、体力查询、用户绑定、抽卡记录、添加表情、欢迎新人、退群通知
  #禁用功能，功能名称,例如：云崽帮助、角色素材、今日素材、养成计算、米游社公告
  disable:
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
    - pixiv-plugin
  groupCD: 100
  addLimit: 0

# 群单独设置，自动覆盖默认值
123456:
  groupGlobalCD: 0 # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 1000 # 群聊中个人操作冷却时间，单位毫秒
  groupCD: 1000
546887365:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 1000
  onlyReplyAt: 0
  imgMaxSize: 2
  addPrivate: 1
  disable:
    - "[鸢尾花插件]进退群群通知"
    - 欢迎新人
    - 退群通知
    - 表情包meme
    - 牛牛
  groupCD: 100
571436194:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 1000
  imgAddLimit: 0
  imgMaxSize: 2
  addPrivate: 1
  disable:
    - bilitv-ll
    - "[鸢尾花插件]进退群群通知"
    - 欢迎新人
    - 退群通知
  groupCD: 100
697922067:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 100
  onlyReplyAt: 0
  imgAddLimit: 2
  imgMaxSize: 2
  disable:
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
    - 欢迎新人
    - bilitv-ll
  groupCD: 100
781047800:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 100
  onlyReplyAt: 0
  imgAddLimit: 2
  imgMaxSize: 2
  disable:
    - bilitv-ll
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
  groupCD: 100
946431041:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 1000
  onlyReplyAt: 0
  imgAddLimit: 2
  imgMaxSize: 2
  addPrivate: 1
  disable:
    - ChatGPT-Plugin 娱乐小功能
    - bilitv-ll
    - ys-woc-Reborn
    - jmcomic
    - JMComic
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
  groupCD: 100
824725200:
  __place__: 0
  disable:
    - ChatGPT-Plugin 娱乐小功能
  groupCD: 100
1031057419:
  __place__: 0
  imgAddLimit: 2
  imgMaxSize: 2
  disable:
    - bilitv-ll
    - bilitv
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
  groupGlobalCD: 1000
  singleCD: 1000
  groupCD: 100
327074629:
  __place__: 0
  groupGlobalCD: 1000
  singleCD: 1000
  disable:
    - "[鸢尾花插件]今日运势"
    - bilitv-ll
    - ChatGPT-Plugin 娱乐小功能
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
  groupCD: 1000
671549425:
  __place__: 0
  groupCD: 100
  singleCD: 1000
  disable:
    - 一眼丁真
    - memes制作
    - 牛牛
    - 牛牛-怀孕
    - 牛牛-日历查看
    - 牛牛-击剑与事件
    - 牛牛-搞钱
    - 牛牛-结婚
    - 牛牛-外出
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
223296599:
  __place__: 0
  groupCD: 100
  singleCD: 1000
  onlyReplyAt: 0
  addLimit: 0
  addPrivate: 1
  disable:
    - bilitv-ll
    - ys-woc-Reborn
    - 牛牛-击剑与事件
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
892470787:
  __place__: 0
  groupCD: 100
  singleCD: 100
  disable:
    - jmcomic
    - JMComic
    - "[鸢尾花插件]进退群群通知"
    - 退群通知
