# 是否自动同意加好友 1-同意 0-不处理
autoFriend: 1
# 是否自动退群人数，当被好友拉进群时，群人数小于配置值自动退出， 默认50，0则不处理
autoQuit: 5
# 主人帐号
masterQQ:
  - 2818259462
# Bot账号:主人帐号
master:
  - stdin:stdin
  - 169965626:2818259462
  - 3762153943:2818259462

# 禁用私聊功能 true：私聊只接受ck以及抽卡链接（Bot主人不受限制），false：私聊可以触发全部指令，默认false
disablePrivate: false
# 禁用私聊Bot提示内容
disableMsg: "私聊功能已禁用，仅支持发送cookie，抽卡记录链接，记录日志文件"
# 私聊通行字符串
disableAdopt:
  - stoken

#白名单群
whiteGroup: []

whiteUser: []

blackGroup:
  - 213938015
#黑名单用户
blackUser: []
